package fr.univ_lyon1.m2ti.services.paiement;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.0.redhat-60024
 * 2014-01-02T23:00:35.815+01:00
 * Generated source version: 2.6.0.redhat-60024
 * 
 */
@WebService(targetNamespace = "http://www.univ-lyon1.fr/M2TI/services/paiement", name = "PaiementPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PaiementPortType {

    @WebResult(name = "reponse-paiement", targetNamespace = "http://www.univ-lyon1.fr/M2TI/services/paiement", partName = "parameters")
    @WebMethod(operationName = "PaiementOperation", action = "http://www.univ-lyon1.fr/M2TI/services/paiement/PaiementOperation")
    public ReponsePaiement paiementOperation(
        @WebParam(partName = "parameters", name = "paiement", targetNamespace = "http://www.univ-lyon1.fr/M2TI/services/paiement")
        Paiement parameters
    );
}
