package fr.univ_lyon1.m2ti.services.paiement;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.0.redhat-60024
 * 2014-01-02T23:00:35.819+01:00
 * Generated source version: 2.6.0.redhat-60024
 * 
 */
@WebServiceClient(name = "Paiement", 
                  wsdlLocation = "file:/home/sereivuth/Desktop/SW/SW_TIW5_Projet/router-camel/src/main/resources/wsdl/Paiement.wsdl",
                  targetNamespace = "http://www.univ-lyon1.fr/M2TI/services/paiement") 
public class Paiement_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.univ-lyon1.fr/M2TI/services/paiement", "Paiement");
    public final static QName PaiementSOAPPort = new QName("http://www.univ-lyon1.fr/M2TI/services/paiement", "PaiementSOAPPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/sereivuth/Desktop/SW/SW_TIW5_Projet/router-camel/src/main/resources/wsdl/Paiement.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Paiement_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/sereivuth/Desktop/SW/SW_TIW5_Projet/router-camel/src/main/resources/wsdl/Paiement.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Paiement_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Paiement_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Paiement_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns PaiementPortType
     */
    @WebEndpoint(name = "PaiementSOAPPort")
    public PaiementPortType getPaiementSOAPPort() {
        return super.getPort(PaiementSOAPPort, PaiementPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaiementPortType
     */
    @WebEndpoint(name = "PaiementSOAPPort")
    public PaiementPortType getPaiementSOAPPort(WebServiceFeature... features) {
        return super.getPort(PaiementSOAPPort, PaiementPortType.class, features);
    }

}
