
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package fr.univ_lyon1.m2ti.services.paiement;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.0.redhat-60024
 * 2014-01-02T23:00:35.808+01:00
 * Generated source version: 2.6.0.redhat-60024
 * 
 */

@javax.jws.WebService(
                      serviceName = "Paiement",
                      portName = "PaiementSOAPPort",
                      targetNamespace = "http://www.univ-lyon1.fr/M2TI/services/paiement",
                      wsdlLocation = "file:/home/sereivuth/Desktop/SW/SW_TIW5_Projet/router-camel/src/main/resources/wsdl/Paiement.wsdl",
                      endpointInterface = "fr.univ_lyon1.m2ti.services.paiement.PaiementPortType")
                      
public class PaiementPortTypeImpl implements PaiementPortType {

    private static final Logger LOG = Logger.getLogger(PaiementPortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see fr.univ_lyon1.m2ti.services.paiement.PaiementPortType#paiementOperation(fr.univ_lyon1.m2ti.services.paiement.Paiement  parameters )*
     */
    public fr.univ_lyon1.m2ti.services.paiement.ReponsePaiement paiementOperation(Paiement parameters) { 
        LOG.info("Executing operation paiementOperation");
        System.out.println(parameters);
        try {
            fr.univ_lyon1.m2ti.services.paiement.ReponsePaiement _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
